import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Check, ChevronRight, Clipboard, FileText, Image, Lightbulb, Save, Send, Sparkles, Trash2, WandSparkles } from 'lucide-react'
import VisualStudio from './VisualStudio.jsx'

const frameworks=[
 {id:'insight',name:'Insight Stack',tag:'Educational',desc:'Hook → shift → framework → takeaway',icon:'01'},
 {id:'myth',name:'Myth Breaker',tag:'Point of view',desc:'Common belief → problem → better approach',icon:'02'},
 {id:'build',name:'Build in Public',tag:'Portfolio',desc:'Problem → decisions → result → learning',icon:'03'},
 {id:'list',name:'Practical Playbook',tag:'Saveable',desc:'Tension → steps → checklist → question',icon:'04'},
]
const tones=['Clear & educational','Personal & reflective','Bold & contrarian','Practical & direct']
const audiences=['AI beginners','Tech professionals','Product & project leaders','Creators & learners']

function createPost({topic,point,audience,tone,framework}){
 const t=topic.trim()||'building useful AI products'; const p=point.trim()||'The tool matters less than the system around it.'
 if(framework==='myth') return `The biggest misconception about ${t}?\n\nThat success comes from adding more tools.\n\nIt sounds reasonable. But it usually creates three problems:\n\n→ More handoffs nobody owns\n→ More output nobody verifies\n→ More complexity before value\n\nA better question is not “Which tool should we add?”\n\nAsk:\n• What problem are we solving?\n• What evidence would prove it works?\n• Where must a human stay responsible?\n\n${p}\n\nWhat misconception do you keep seeing in your work?\n\n#ArtificialIntelligence #Learning #FutureOfWork`
 if(framework==='build') return `I built a small project around ${t}.\n\nNot because the world needed another demo.\n\nI wanted to understand what happens between an idea and a working system.\n\nWhat I changed along the way:\n\n01 — Started with the user’s question\n02 — Removed features that looked good but taught nothing\n03 — Made the difficult concepts visual\n04 — Tested every flow as a first-time visitor\n\nThe biggest lesson?\n\n${p}\n\nBuilding in public turns vague knowledge into visible proof of work.\n\nWhat are you learning by building right now?\n\n#BuildInPublic #AI #WebDevelopment #Learning`
 if(framework==='list') return `${t} is easier to understand when you stop treating it as one big topic.\n\nUse this simple learning sequence:\n\n1. Understand the problem\n2. Learn the smallest useful concept\n3. See one visual example\n4. Practice with a real scenario\n5. Explain it without jargon\n\nBefore moving forward, check:\n\n✓ Can I explain why it matters?\n✓ Can I name one limitation?\n✓ Can I apply it to my work?\n\n${p}\n\nSave this for your next learning session. What would you add?\n\n#Learning #ArtificialIntelligence #CareerGrowth`
 return `${t} just became more important—and more misunderstood.\n\nThe people who benefit most will not be those who memorize the most terminology.\n\nThey will understand how the pieces connect.\n\nHere is the simple map:\n\n→ The goal defines what “good” means\n→ Data provides examples\n→ A model learns a pattern\n→ Evaluation reveals where it fails\n→ Human judgement decides whether it is useful\n\n${p}\n\nThe takeaway:\n\nDon’t learn isolated tools. Learn the decisions that connect them.\n\nWhich part deserves a deeper breakdown next?\n\n#AI #MachineLearning #Technology #ContinuousLearning`
}

function App(){
 const [tab,setTab]=useState('compose'); const [framework,setFramework]=useState('insight'); const [topic,setTopic]=useState('How machines learn'); const [point,setPoint]=useState('Good learning connects concepts instead of presenting isolated definitions.'); const [audience,setAudience]=useState(audiences[0]); const [tone,setTone]=useState(tones[0]); const [post,setPost]=useState(''); const [saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem('signal-drafts')||'[]')); const [copied,setCopied]=useState(false)
 useEffect(()=>localStorage.setItem('signal-drafts',JSON.stringify(saved)),[saved])
 useEffect(()=>{if(!post)setPost(createPost({topic,point,audience,tone,framework}))},[])
 const stats=useMemo(()=>({chars:post.length,words:post.trim()?post.trim().split(/\s+/).length:0,read:Math.max(1,Math.ceil(post.trim().split(/\s+/).length/180))}),[post])
 const generate=()=>setPost(createPost({topic,point,audience,tone,framework})); const save=()=>setSaved([{id:Date.now(),topic,post,date:new Date().toLocaleDateString(),status:'Draft'},...saved]); const copy=async()=>{await navigator.clipboard.writeText(post);setCopied(true);setTimeout(()=>setCopied(false),1600)}
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><span>S</span><div><b>SIGNAL</b><small>CONTENT STUDIO</small></div></div><nav>{[['compose',WandSparkles,'Compose'],['visuals',Image,'Visuals & GIF'],['calendar',CalendarDays,'Calendar'],['drafts,',FileText,'Drafts']].map(([id,I,label])=><button key={id} className={tab===id.replace(',','')?'active':''} onClick={()=>setTab(id.replace(',',''))}><I size={18}/>{label}</button>)}</nav><div className="side-note"><Sparkles size={17}/><b>Human first</b><p>Draft with structure. Review with judgement. Publish manually.</p></div><footer>NO LINKEDIN CREDENTIALS<br/>STORED OR REQUIRED</footer></aside>
  <main><header className="topbar"><div><span className="live-dot"/> PRIVATE WORKSPACE</div><div className="top-actions"><button onClick={save}><Save size={15}/> Save draft</button><button className="publish" onClick={()=>window.open('https://www.linkedin.com/feed/?shareActive=true','_blank')}><Send size={15}/> Open LinkedIn</button></div></header>
   {tab==='compose'&&<div className="workspace"><section className="composer"><div className="section-title"><small>01 / STRATEGY</small><h1>Turn one idea into<br/><em>a post worth reading.</em></h1><p>Choose a proven information structure, add your real experience, then edit until it sounds like you.</p></div><div className="form-block"><label>What do you want to write about?</label><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. What I learned building an AI course"/><label>Your original point or experience</label><textarea value={point} onChange={e=>setPoint(e.target.value)} rows="3"/><div className="two-cols"><div><label>Audience</label><select value={audience} onChange={e=>setAudience(e.target.value)}>{audiences.map(x=><option key={x}>{x}</option>)}</select></div><div><label>Tone</label><select value={tone} onChange={e=>setTone(e.target.value)}>{tones.map(x=><option key={x}>{x}</option>)}</select></div></div></div><div className="frameworks"><div className="block-head"><div><small>02 / STRUCTURE</small><h2>Choose a framework</h2></div><Lightbulb size={20}/></div>{frameworks.map(f=><button key={f.id} onClick={()=>setFramework(f.id)} className={framework===f.id?'active':''}><span>{f.icon}</span><div><b>{f.name}</b><small>{f.desc}</small></div><em>{f.tag}</em><Check size={16}/></button>)}</div><button className="generate" onClick={generate}><Sparkles size={18}/> Generate structured draft <ChevronRight size={17}/></button></section>
    <section className="preview"><div className="preview-head"><div><small>LIVE PREVIEW</small><span>LinkedIn text post</span></div><button onClick={copy}>{copied?<Check size={16}/>:<Clipboard size={16}/>} {copied?'Copied':'Copy'}</button></div><div className="post-card"><div className="profile"><div className="avatar">LS</div><div><b>Lalit Singh</b><span>Learning AI by building · Just now · ◉</span></div></div><textarea value={post} onChange={e=>setPost(e.target.value)}/><div className="post-metrics"><span>{stats.chars} characters</span><span>{stats.words} words</span><span>~{stats.read} min read</span></div></div><div className="quality"><div><b>Post quality</b><span>Strong foundation</span></div>{[['Clear first-line hook',true],['Scannable line length',true],['Original point included',point.length>15],['Ends with a conversation',post.includes('?')]].map(([x,ok])=><p key={x} className={ok?'ok':''}><i>{ok?'✓':'·'}</i>{x}</p>)}</div></section></div>}
   {tab==='visuals'&&<VisualStudio/>}{tab==='calendar'&&<Calendar saved={saved}/>} {tab==='drafts'&&<Drafts saved={saved} setSaved={setSaved} setPost={setPost} setTab={setTab}/>} 
  </main>
 </div>
}

function Calendar({saved}){const days=Array.from({length:28},(_,i)=>i+1);return <div className="page-panel"><div className="page-heading"><small>CONTENT RHYTHM</small><h1>Plan consistency,<br/><em>not noise.</em></h1><p>A simple calendar for ideas and approved drafts. Publishing remains manual.</p></div><div className="calendar-grid">{days.map(d=><div key={d}><span>JUL {d}</span>{d===14&&<b className="event purple">AI learning lesson</b>}{d===18&&<b className="event blue">Build update</b>}{d===23&&<b className="event green">Practical playbook</b>}</div>)}</div></div>}
function Drafts({saved,setSaved,setPost,setTab}){return <div className="page-panel"><div className="page-heading"><small>YOUR LIBRARY</small><h1>Saved drafts.</h1><p>Stored only in this browser. No account, database, or LinkedIn access required.</p></div><div className="draft-list">{saved.length?saved.map(x=><article key={x.id}><span>{x.date}</span><div><b>{x.topic}</b><p>{x.post.slice(0,150)}…</p></div><button onClick={()=>{setPost(x.post);setTab('compose')}}>Edit</button><button onClick={()=>setSaved(saved.filter(y=>y.id!==x.id))}><Trash2 size={15}/></button></article>):<div className="empty"><FileText size={35}/><h2>No saved drafts yet</h2><p>Create a post and select “Save draft.”</p></div>}</div></div>}
export default App
